---
- hosts: localhost
  remote_user: vagrant
  sudo: yes
  gather_facts: false
  tasks:
    - name: colorize prompt
      lineinfile: dest=/home/vagrant/.bashrc regexp='#force_color_prompt(.*)$' line='force_color_prompt\1' backrefs=yes

    - name: update distro
      apt: upgrade=dist update_cache=true cache_valid_time=3600

    - name: ensure apache2 is at latest version
      apt: pkg={{ item }} state=latest update_cache=true cache_valid_time=3600
      with_items:
        - apache2
        - php5
        - libapache2-mod-php5
        - mysql-server
        - libapache2-mod-auth-mysql
        - php5-mysql
        - phpmyadmin
        - python-mysqldb

    - name: ensure that ServerName is localhost
      lineinfile: dest=/etc/apache2/conf.d/name line='ServerName localhost' create=yes state=present owner=root group=root mode=0644
      notify:
        - restart apache2

    - name: ensure apache2 is running
      service: name=apache2 state=started

    - name: set mysql root password
      mysql_user: name=root password=root

    - name: create posticum database
      mysql_db: login_user=root login_password=root name=posticum

    - name: create posticum user
      mysql_user: login_user=root login_password=root name=post password=dev priv=posticum.*:ALL

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
