---
- name: ensure apache2 is at latest version
  apt: pkg={{ item }} state=latest update_cache=true cache_valid_time=3600
  with_items:
    - apache2
    - php5
    - libapache2-mod-php5

- name: ensure that ServerName is localhost
  lineinfile: dest=/etc/apache2/conf.d/name line='ServerName localhost' create=yes state=present owner=root group=root mode=0644
  notify:
    - restart apache2

- name: ensure apache2 is running
  service: name=apache2 state=started

- name: copy virtualhost file
  template: src=virtualhost.j2 dest=/etc/apache2/sites-enabled/dev
  notify:
    - restart apache2

- name: disable default site
  file: path=/etc/apache2/sites-enabled/000-default state=absent
  notify:
    - restart apache2

- name: copy php5 development conf
  copy: src=/usr/share/doc/php5-common/examples/php.ini-development dest=/etc/php5/apache2/php.ini
  notify:
    - restart apache2
